# -*- coding: utf-8 -*-
"""공식 5등급(L3 판정) 어휘 1차 보강 배치 - 사람이 직접 작성한 콘텐츠 데이터.

이 파일의 모든 텍스트(학생용 뜻풀이·예문)는 사람(에이전트)이 공식 원문
뜻풀이만 보고 직접 다시 썼다 - 외부 조사·추가 사전 조회 없음(사용자 지시).
공식 원문(official_meaning_short)은 별도 필드로 그대로 보존하고, 학생용
수정안으로 덮어쓰지 않는다.
"""
from __future__ import annotations

# candidate_id는 nikl_grade5_200_full_refresh_20261007.csv와 1:1로 일치해야
# 한다(build_batch1_dryrun.py에서 검증).
ITEMS = [
    dict(candidate_id="G5-8ce1ebfbf28902b8", lemma="개축", pos="명사",
         student_definition="낡거나 허물어진 집이나 건물을 다시 짓거나 고쳐 쌓는 일.",
         example="오래된 학교 건물을 개축하는 공사가 이번 달에 시작되었다."),
    dict(candidate_id="G5-15d9d99fbc5ed1f2", lemma="견학단", pos="명사",
         student_definition="무엇을 직접 보고 배우러 가기 위해 모인 사람들의 모임.",
         example="우리 학교 견학단은 박물관으로 현장 학습을 떠났다."),
    dict(candidate_id="G5-288ade20add47e11", lemma="경조사", pos="명사",
         student_definition="결혼이나 돌잔치처럼 축하할 일과 장례처럼 슬픈 일을 함께 이르는 말.",
         example="할머니는 동네 사람들의 경조사를 빠짐없이 챙기셨다."),
    dict(candidate_id="G5-86ac65ab170bf93b", lemma="고안되다", pos="동사",
         student_definition="생각하고 연구해서 새로운 방법이나 물건이 만들어지다.",
         example="학생들의 안전을 위한 새로운 신호등이 고안되었다.", context_form="고안되었다"),
    dict(candidate_id="G5-b0c32a2b4cac3bd9", lemma="공기주머니", pos="명사",
         student_definition="새의 몸속에서 공기가 드나드는 얇은 주머니 모양의 기관으로, 몸을 가볍게 뜨도록 돕는다.",
         example="새는 공기주머니 덕분에 높은 하늘에서도 가볍게 날 수 있다."),
    dict(candidate_id="G5-bc3d3e5746938ca4", lemma="교직원", pos="명사",
         student_definition="학교에서 가르치는 선생님과 학교 일을 돕는 직원을 모두 합쳐 이르는 말.",
         example="학교 축제에는 학생뿐 아니라 교직원들도 함께 참여했다."),
    dict(candidate_id="G5-9050b15f83fa1e98", lemma="국방력", pos="명사",
         student_definition="나라를 지키기 위한 군사적인 힘.",
         example="그 나라는 국방력을 키우기 위해 많은 예산을 투자했다."),
    dict(candidate_id="G5-40fd9cf0513a6748", lemma="꺼칠하다", pos="형용사",
         student_definition="몸이 마르거나 건강이 안 좋아서 피부나 털에 윤기가 없고 거칠다.",
         example="며칠 밤을 새우고 나니 얼굴이 꺼칠했다.", context_form="꺼칠했다"),
    dict(candidate_id="G5-0b695941ae270b65", lemma="낙엽수", pos="명사",
         student_definition="가을이나 겨울에 잎이 떨어지고 봄이 되면 새잎이 다시 나는 나무.",
         example="은행나무는 가을이 되면 잎이 노랗게 물드는 대표적인 낙엽수이다."),
    dict(candidate_id="G5-c02960d8706f5e30", lemma="내야수", pos="명사",
         student_definition="야구에서 1루, 2루, 3루, 유격 자리를 지키는 선수를 통틀어 이르는 말.",
         example="내야수가 재빠르게 공을 잡아 1루로 던져 아웃시켰다."),
    dict(candidate_id="G5-108296da3208d97a", lemma="노여워하다", pos="동사",
         student_definition="화가 날 만큼 분하거나 섭섭한 마음을 가지다.",
         example="동생은 자기 말을 안 믿어 준다고 몹시 노여워했다.", context_form="노여워했다"),
    dict(candidate_id="G5-a71a19a47aee8d59", lemma="단음", pos="명사",
         student_definition="원래 길게 내는 소리와 달리 짧게 내는 소리.",
         example="선생님께서는 장음과 단음의 차이를 설명하며 낱말의 발음을 들려주셨다."),
    dict(candidate_id="G5-d6add3880c766a14", lemma="대소", pos="명사",
         student_definition="크고 작은 정도. 또는 큰 것과 작은 것.",
         example="회의에서는 문제의 대소를 가리지 않고 모두 의논하기로 했다."),
    dict(candidate_id="G5-85e1f60f7edb514f", lemma="도시민", pos="명사",
         student_definition="도시에서 사는 사람.",
         example="도시민들은 좁은 아파트에서 생활하는 경우가 많다."),
    dict(candidate_id="G5-35d7896d01fecab8", lemma="동지애", pos="명사",
         student_definition="같은 목표를 가지고 함께 노력하는 사람들 사이의 끈끈한 정.",
         example="함께 훈련을 견뎌 낸 선수들 사이에는 끈끈한 동지애가 생겼다."),
    dict(candidate_id="G5-978789e2dc690091", lemma="뒤룩뒤룩", pos="부사",
         student_definition="살이 많이 올라 뚱뚱하고 출렁거리는 모양.",
         example="오랜만에 만난 강아지는 살이 뒤룩뒤룩 쪄 있었다."),
    dict(candidate_id="G5-4d4e81d64548e5c4", lemma="면회하다", pos="동사",
         student_definition="군대나 병원처럼 쉽게 드나들 수 없는 곳에 찾아가서 그 안에 있는 사람을 만나 보다.",
         example="주말에 군대에 간 형을 면회하러 다녀왔다.", context_form="면회하러"),
    dict(candidate_id="G5-be52d7e48cccce04", lemma="모기약", pos="명사",
         student_definition="모기를 쫓거나 없애기 위해 쓰는 약.",
         example="여름밤에는 모기약을 뿌리고 자야 편하게 잘 수 있다."),
    dict(candidate_id="G5-6fbf37d42d4be6ae", lemma="밥투정", pos="명사",
         student_definition="밥을 먹기 싫어하거나 반찬이 마음에 안 든다고 짜증을 부리는 일.",
         example="동생은 채소가 들어간 반찬을 보더니 밥투정을 부렸다."),
    dict(candidate_id="G5-c26610ca828c6022", lemma="범행자", pos="명사",
         student_definition="범죄를 저지른 사람.",
         example="경찰은 범행자의 행적을 CCTV로 추적했다."),
    dict(candidate_id="G5-0fa0e0a975e55d66", lemma="벨기에", pos="명사",
         student_definition="유럽 서북부에 있는 나라 이름.",
         example="벨기에는 네덜란드, 프랑스와 가까운 유럽의 나라이다."),
    dict(candidate_id="G5-effce8eb3869356c", lemma="변성기", pos="명사",
         student_definition="사춘기에 목소리가 변하는 시기.",
         example="변성기를 겪으면서 형의 목소리가 많이 낮아졌다."),
    dict(candidate_id="G5-8eb7191f007f9d70", lemma="보국안민", pos="명사",
         student_definition="나라를 위해 힘쓰고 백성을 편안하게 살게 하는 일.",
         example="동학 농민 운동은 보국안민을 외치며 일어난 사건이다."),
    dict(candidate_id="G5-92af004a38b66494", lemma="부촌", pos="명사",
         student_definition="부유한 사람들이 많이 사는 마을이나 지역.",
         example="그 동네는 큰 저택들이 많아 부촌으로 알려져 있다."),
    dict(candidate_id="G5-2df2bb0b3bb9a077", lemma="브레인스토밍", pos="명사",
         student_definition="여러 사람이 자유롭게 의견을 내면서 좋은 생각을 찾아내는 방법.",
         example="모둠 활동을 시작하기 전에 브레인스토밍으로 다양한 의견을 모았다."),
    dict(candidate_id="G5-795351a35677b337", lemma="살상하다", pos="동사",
         student_definition="사람을 죽이거나 다치게 하다.",
         example="그 무기는 많은 사람을 살상할 수 있어 국제적으로 사용이 금지되었다.", context_form="살상할"),
    dict(candidate_id="G5-dd925e505c88b4a6", lemma="삼중창", pos="명사",
         student_definition="서로 다른 음을 맡은 세 사람이 함께 부르는 노래.",
         example="합창 대회에서 세 친구가 아름다운 삼중창을 선보였다."),
    dict(candidate_id="G5-9ebfb75821a2164a", lemma="상용", pos="명사",
         student_definition="날마다 흔히 사용함.",
         example="이 표현은 뉴스에서도 상용으로 쓰이는 말이다."),
    dict(candidate_id="G5-7553747fc991504b", lemma="서넛", pos="수사",
         student_definition="셋이나 넷쯤 되는 수.",
         example="교실에는 아직 서넛 정도의 학생만 남아 있었다."),
    dict(candidate_id="G5-5047276d84610bfb", lemma="소송비", pos="명사",
         student_definition="소송을 진행하고 재판을 받기 위해 드는 비용.",
         example="소송비가 많이 들어 합의로 문제를 해결하기로 했다."),
]

assert len(ITEMS) == 30
assert len({it["candidate_id"] for it in ITEMS}) == 30
assert len({it["lemma"] for it in ITEMS}) == 30
